### ISSUE TITLE
用了以后要同时开安卓模拟器才能到60fps

### ISSUE THREAD

**Issue by tony950309** [ckeleshi/FFOPatcher#3]
楼主你好,感谢分享.
我遇到个问题.
我系统是win10企业版19044.cpu11800hq, gpu3080 laptop
显卡驱动472.12 (虽然并没用显卡)

游戏是用核显开的.
但是使用你分享的脚本后,op模式900p下还是只有40fps上下. 此时cpu战用3.7%, 核显占用22%左右.

只有我再开个安卓模拟器(雷神模拟器),模拟器不需要打开任何app.游戏就能稳定60+,非常流畅.
这个时候ffo的cpu战用到4.3%左右,核显(gpu0)占用能到37%左右. 

给我的感觉就是不开安卓模拟器,游戏还是吃不满资源
![image](https://user-images.githubusercontent.com/22861292/156604052-e419c3a4-371b-4861-9de4-ba500c97a212.png)

电脑资源够用.本来这样开着也不影响啥,问题是,极少数的情况,会出现安卓模拟器和ffo窗口同时奔溃的情况.不会提示错误报告.直接就窗口消失.所以来请教下可能的原因和解决方案?

ps:这个问题我从年初开始用的时候就有,你3/2更新的说现在游戏掉帧的情况我并没有遇到...我好多朋友也用这个脚本(再次感谢分享),但是他们都没我这个问题...有一个人是显示器刷新率设置的低,改到60就好了..我一直是60hz..怎么改都没用.

提前感谢

**Comment by ckeleshi** [comment]
我在1月退游之前的所有游戏版本:
用补丁稳定61fps，不用补丁稳定33fps

现在更新过几次之后:
用补丁只有40+fps，不用补丁24fps，而且fps会以5+的幅度不停变化。
应该是游戏更新之后有些逻辑变了，要重新研究下。

**Comment by ckeleshi** [comment]
@tony950309 已经修复

**Comment by tony950309** [comment]
弱弱的问个和这个脚本没关系的问题...(如果楼主了解的话)
我想写个后台操作键鼠的脚本.网上教程也不少
用python的话基本都是调用win32的sendMessage或者PostMessage.比如:
PostMessageW(handle, WM_MOUSEMOVE, win32con.MK_LBUTTON, win32api.MAKELONG(x, y))
或者
win32gui.SendMessage(hWnd, win32con.WM_LBUTTONDOWN, win32con.MK_LBUTTON, win32api.MAKELONG(xy.x, xy.y+50))
我遇到的问题是窗口内(不管ffo是前台还是后台),能点击,但是位置是目前实际鼠标的位置而不是我传入的坐标.

当然用pyautogui之类的来前台操作是完全没问题.后台操作键盘也没问题.就是这个鼠标很奇怪...

**Comment by ckeleshi** [comment]
不了解WM_LBUTTONDOWN支不支持同时传坐标，有可能是不支持/参数传得不对/ffo有限制，可以先把光标移到目的位置再点
也有可能最小化窗口根本不会处理鼠标位置的消息，试试操作一个窗口的时候先把它置为前台

**Comment by tony950309** [comment]
up你好.我之前遇到的不开安卓模拟器到不了60fps的问题原因找到了.
是没开hyper-V的原因,bios里面可以打开

(今天鼓捣wsl虚拟机和安卓模拟器冲突以后研究了下发现的)

如果win10用户遇到和我一样的问题,用了插件.游戏不蓝底板了.硬件资源占用不高,但是fps上不去.在排除屏幕刷新率和nVidia控制面板刷新率设置问题后可以看看是不是bios的hyper-V(或者VT)没开.具体是啥内容自己搜
